import { useMemo, useState } from 'react'
import { Accordion, Button, Card, Checkbox, Dialog, Tabs, Tag, Toggle } from '@demo/ui-react'
import type { TagTone } from '@demo/ui-core'

const users = [
  { id: 'u-1001', name: 'Lin Chen', team: 'Autonomous Tooling', role: 'Admin', status: 'Active', risk: 'Low' },
  { id: 'u-1002', name: 'Maya Zhang', team: 'Data Platform', role: 'Editor', status: 'Active', risk: 'Medium' },
  { id: 'u-1003', name: 'Noah Wang', team: 'Simulation', role: 'Viewer', status: 'Paused', risk: 'Low' },
  { id: 'u-1004', name: 'Iris Liu', team: 'Annotation Ops', role: 'Reviewer', status: 'Active', risk: 'High' },
]

const policies = [
  { value: 'schema', title: 'Schema guard', content: 'Generated pages must pass component manifest validation before code output.' },
  { value: 'theme', title: 'Theme guard', content: 'Business pages may switch theme tokens, but should not redefine component internals.' },
  { value: 'runtime', title: 'Runtime guard', content: 'React, Vue and Web Component renderers share contracts but keep their own runtime model.' },
]

const riskTone: Record<string, TagTone> = {
  Low: 'info',
  Medium: 'warning',
  High: 'danger',
}

const statusTone: Record<string, TagTone> = {
  Active: 'success',
  Paused: 'neutral',
}

export default function AdminView() {
  const [selected, setSelected] = useState<string[]>(['u-1001'])
  const [safeMode, setSafeMode] = useState(true)

  const selectedCount = selected.length
  const rows = useMemo(() => users, [])

  function toggleUser(id: string, checked: boolean) {
    setSelected(current => checked ? [...new Set([...current, id])] : current.filter(item => item !== id))
  }

  return (
    <>
      <p className="eyebrow">BUSINESS PAGE / GENERATED BY UI PACKAGE</p>
      <section className="admin-hero">
        <div>
          <h1>Team Access</h1>
          <p className="intro">A management page assembled from packaged components only. Table is intentionally skipped until we introduce TanStack.</p>
        </div>
        <div className="admin-actions">
          <Button variant="secondary">Export</Button>
          <Dialog
            trigger="Invite member"
            title="Invite member"
            description="This dialog is provided by the React renderer wrapping Ark UI. Form components are not introduced yet, so this demo keeps the body simple."
          >
            <p className="admin-dialog-note">Next step: add Input and Select wrappers, then this dialog can become a real invite form.</p>
            <Button>Confirm invite</Button>
          </Dialog>
        </div>
      </section>

      <section className="admin-metrics">
        <Card title="Total members"><strong className="admin-metric-value">{rows.length}</strong></Card>
        <Card title="Selected"><strong className="admin-metric-value">{selectedCount}</strong></Card>
        <Card title="High risk"><strong className="admin-metric-value">{rows.filter(row => row.risk === 'High').length}</strong></Card>
      </section>

      <Card className="admin-panel">
        <div className="admin-toolbar">
          <div>
            <h2>Members</h2>
            <p>Cards and tags are now packaged components. Complex table is reserved for TanStack later.</p>
          </div>
          <Toggle checked={safeMode} onCheckedChange={setSafeMode}>Safe mode</Toggle>
        </div>

        <Tabs
          defaultValue="members"
          items={[
            {
              value: 'members',
              label: 'Members',
              content: (
                <div className="admin-member-grid">
                  {rows.map(row => (
                    <Card variant="muted" className="admin-member-card" key={row.id}>
                      <div className="admin-member-head">
                        <Checkbox
                          label=""
                          checked={selected.includes(row.id)}
                          onCheckedChange={checked => toggleUser(row.id, checked)}
                        />
                        <div>
                          <strong>{row.name}</strong>
                          <p>{row.team}</p>
                        </div>
                      </div>
                      <div className="admin-member-meta">
                        <span>Role: {row.role}</span>
                        <Tag tone={statusTone[row.status]}>{row.status}</Tag>
                        <Tag tone={riskTone[row.risk]}>{row.risk} risk</Tag>
                      </div>
                    </Card>
                  ))}
                </div>
              ),
            },
            {
              value: 'policies',
              label: 'Policies',
              content: <Accordion multiple items={policies} />,
            },
            {
              value: 'activity',
              label: 'Activity',
              content: (
                <ul className="admin-feed">
                  <li>AI generated a page-level UI schema.</li>
                  <li>Renderer mapped schema nodes to packaged components.</li>
                  <li>Theme tokens applied without changing business code.</li>
                </ul>
              ),
            },
          ]}
        />
      </Card>
    </>
  )
}
